### ISSUE TITLE
Asthetic issues 

### ISSUE THREAD

**Issue by SimonMalla** [Ichha21/Assignment-Space#1]
![image](https://github.com/Ichha21/Assignment-Space/assets/119477924/a7bd005e-d340-4794-adf3-950a686bf258)
please align all the boxes and buttons correctly to make more astheticly pleasing

**Comment by AnitaWaiba** [comment]
![image](https://github.com/Ichha21/Assignment-Space/assets/119423817/abdf50ae-f3cf-43c0-84bd-beae6b8850ce)
