### ISSUE TITLE
Empty Password Field

### ISSUE THREAD

**Issue by SimonMalla** [Ichha21/Assignment-Space#10]
![image](https://github.com/Ichha21/Assignment-Space/assets/119477924/b15c7167-7571-4d39-a8e3-9a08839a453a)
Here there is no password entered in the password field but instead of giving "please fill all the boxes" message it shows no response.

**Comment by Roshanbohara10** [comment]
![image](https://github.com/Ichha21/Assignment-Space/assets/119285937/b13e5526-f579-41c9-a1cb-e0dc48ed47bd)
Adjust the code on signup page to redirect smoothly on login page
