### ISSUE TITLE
Issue for front end (Anita Waiba )

### ISSUE THREAD

**Issue by Ichha21** [Ichha21/Assignment-Space#11]
![image](https://github.com/Ichha21/Assignment-Space/assets/167756535/b5b5708d-e21d-4abb-99a3-4f6d7c2471e1)
The search button that you have added is of no use you can remove that .

**Comment by AnitaWaiba** [comment]
![image](https://github.com/Ichha21/Assignment-Space/assets/119423817/0b190520-1a2a-4e6e-b7d2-df8446762e55)
