### ISSUE TITLE
Issues with Authentication while trying to log in

### ISSUE THREAD

**Issue by SimonMalla** [Ichha21/Assignment-Space#12]
![image](https://github.com/Ichha21/Assignment-Space/assets/119477924/d8cf6590-6546-4376-95ae-b7c2f49f7f10)
authentication bugs in Django can arise due to various issues such as misconfigured settings, URLs, views, middleware, session configuration, permissions, and third-party authentication. You need to prevent this from happening

**Comment by Uttamluffy** [comment]
![Uploading image.png…]()

**Comment by Uttamluffy** [comment]
done
