### ISSUE TITLE
Empty homework submission

### ISSUE THREAD

**Issue by SimonMalla** [Ichha21/Assignment-Space#13]
![image](https://github.com/Ichha21/Assignment-Space/assets/119477924/b4c16037-69f2-4898-8e33-1db1c0669fd9)
Even when a student does not attach a file while submitting it still goes through and is saved as a empty assignment

**Comment by Uttamluffy** [comment]
![image](https://github.com/Ichha21/Assignment-Space/assets/127734652/720df025-e8b6-48c2-b553-801237b15681)

**Comment by Uttamluffy** [comment]
solve
