### ISSUE TITLE
issue for backend developer 

### ISSUE THREAD

**Issue by Ichha21** [Ichha21/Assignment-Space#14]
![image](https://github.com/Ichha21/Assignment-Space/assets/167756535/8ec10342-ec17-4ef5-b708-49d005528e4a)
notification didn't show up in the student page after review teacher provide feedback

**Comment by Roshanbohara10** [comment]
![image](https://github.com/Ichha21/Assignment-Space/assets/119285937/ee8e8cdc-08b6-490f-89be-f21bd404e9bd)
done
made some changes on code now notification is working perfectly
