### ISSUE TITLE
Sign up page spacing bug

### ISSUE THREAD

**Issue by SimonMalla** [Ichha21/Assignment-Space#2]
![image](https://github.com/Ichha21/Assignment-Space/assets/119477924/710b55ad-f962-4475-bc74-6eaa46407615)
please make the sign up box wider and more visually apealing

**Comment by AnitaWaiba** [comment]
![image](https://github.com/Ichha21/Assignment-Space/assets/119423817/57afe6f4-cabf-44de-a90d-2863a72cb77e)
