### ISSUE TITLE
Dark mode error

### ISSUE THREAD

**Issue by SimonMalla** [Ichha21/Assignment-Space#3]
![image](https://github.com/Ichha21/Assignment-Space/assets/119477924/017cda6f-8891-431c-8a22-2ee56ac6e3bc)
clicking the darkmode button should apply darkmode to the page

**Comment by AnitaWaiba** [comment]
![image](https://github.com/Ichha21/Assignment-Space/assets/119423817/3027503d-fc9f-4036-a0fe-23ae70119f62)
