### ISSUE TITLE
Teacher info bug

### ISSUE THREAD

**Issue by SimonMalla** [Ichha21/Assignment-Space#4]
![image](https://github.com/Ichha21/Assignment-Space/assets/119477924/1dc63c53-1b2f-4f4a-ac43-ae6a8eca36e4)
![image](https://github.com/Ichha21/Assignment-Space/assets/119477924/de0b8643-6ab4-411b-ab44-7883d7481fb7)
clicking on teacher should redirect to a page showing the information of the teachers, here it redirects to the wrong page, please fix.

**Comment by AnitaWaiba** [comment]
![image](https://github.com/Ichha21/Assignment-Space/assets/119423817/a370ff43-fdeb-4b0f-b306-9626ae393e8a)
