### ISSUE TITLE
Student info bug

### ISSUE THREAD

**Issue by SimonMalla** [Ichha21/Assignment-Space#5]
![image](https://github.com/Ichha21/Assignment-Space/assets/119477924/bd35ae91-5b35-42f4-8c4c-7e6764e29c49)
Clicking on student from the admin dashboard should display the student info but here an erorr occurs

**Comment by AnitaWaiba** [comment]
![image](https://github.com/Ichha21/Assignment-Space/assets/119423817/1c5a7d88-2bf7-4ff9-9397-930e23e8ed01)
