### ISSUE TITLE
Inconsistent Log in page

### ISSUE THREAD

**Issue by SimonMalla** [Ichha21/Assignment-Space#6]
![image](https://github.com/Ichha21/Assignment-Space/assets/119477924/2eb0acb7-b496-4d99-a07b-cc80bfccf948)
The log in page is visually inconsistent please make the box more consistent and visually apealing

**Comment by AnitaWaiba** [comment]
![image](https://github.com/Ichha21/Assignment-Space/assets/119423817/1bd586ea-386a-450a-9c1a-687286f1fd0f)
