### ISSUE TITLE
Log in page error

### ISSUE THREAD

**Issue by SimonMalla** [Ichha21/Assignment-Space#7]
![image](https://github.com/Ichha21/Assignment-Space/assets/119477924/415b9923-05c2-49f9-8ddb-b01fc7044927)
Should show "please fill up the boxex" message but it does not show any error message.

**Comment by Roshanbohara10** [comment]
![image](https://github.com/Ichha21/Assignment-Space/assets/119285937/d9f9b024-9e76-432e-952d-3178145c201a)
made some chnages to show error message
