### ISSUE TITLE
Invalid username bug

### ISSUE THREAD

**Issue by SimonMalla** [Ichha21/Assignment-Space#8]
![image](https://github.com/Ichha21/Assignment-Space/assets/119477924/8d897c51-a189-4bd1-b15b-7224762aff03)
Should show " invalid username" message, but it does not show any message

**Comment by Roshanbohara10** [comment]
solved
![image](https://github.com/Ichha21/Assignment-Space/assets/119285937/e0abfa0a-cc1b-43b4-974b-6e1a164e40b9)
